name: Trigger auto deployment for rz-my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rz-my-container-app-AutoDeployTrigger-b6c8e63e-eaf8-4f23-aa42-26934adcc95e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RZMYCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RZMYCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RZMYCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: rzminihackdemo.azurecr.io
          registryUsername: ${{ secrets.RZMYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RZMYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: rz-my-container-app
          resourceGroup: rz-rg-my-container-apps
          imageToBuild: rzminihackdemo.azurecr.io/rz-my-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


